// js/gachaConfig.js
export const machines = [
    {
        name: "12 Zodiac",
        themeColors: { base: 0xf97316, top: 0x6366f1 },
        requiredStoneId: 0,
        dropRates: [
            { rarity: "LEGENDARY", rate: 0.02, color: "#FFD700" },
            { rarity: "EPIC", rate: 0.05, color: "#9400D3" },
            { rarity: "RARE", rate: 0.13, color: "#1E90FF" },
            { rarity: "UNCOMMON", rate: 0.25, color: "#32CD32" },
            { rarity: "COMMON", rate: 0.55, color: "#A9A9A9" },
        ],
        itemPool: [
            { name: "5. Dragon", rarity: "LEGENDARY", img: "https://img2.pic.in.th/pic/5.--Dragon.png" },
            { name: "3. Tiger", rarity: "EPIC", img: "https://img5.pic.in.th/file/secure-sv1/3.--Tiger.png" },
            { name: "7. Horse", rarity: "EPIC", img: "https://img5.pic.in.th/file/secure-sv1/7.--Horse.png" },
            { name: "10. Rooster", rarity: "RARE", img: "https://img2.pic.in.th/pic/10.--Rooster.png" },
            { name: "9. Monkey", rarity: "RARE", img: "https://img5.pic.in.th/file/secure-sv1/9.--Monkey.png" },
            { name: "12. Pig", rarity: "RARE", img: "https://img5.pic.in.th/file/secure-sv1/12.--Pig.png" },
            { name: "6. Snake", rarity: "UNCOMMON", img: "https://img5.pic.in.th/file/secure-sv1/6.--Snake.png" },
            { name: "8. Goat", rarity: "UNCOMMON", img: "https://img2.pic.in.th/pic/8.--Goat.png" },
            { name: "11. Dog", rarity: "UNCOMMON", img: "https://img2.pic.in.th/pic/11.--Dog.png" },
            { name: "4. Rabbit", rarity: "COMMON", img: "https://img2.pic.in.th/pic/4.--Rabbit.png" },
            { name: "1. Rat", rarity: "COMMON", img: "https://img5.pic.in.th/file/secure-sv1/1.--Rat.png" },
            { name: "2. Ox", rarity: "COMMON", img: "https://img2.pic.in.th/pic/2.--Ox.png" },
        ]
    },
    {
        name: "13 Kingdom",
        themeColors: { base: 0x22c55e, top: 0x0ea5e9 },
        requiredStoneId: 1,
        dropRates: [ { rarity: "LEGENDARY", rate: 0.02, color: "#FFD700" }, { rarity: "EPIC", rate: 0.05, color: "#9400D3" }, { rarity: "RARE", rate: 0.13, color: "#1E90FF" }, { rarity: "UNCOMMON", rate: 0.25, color: "#32CD32" }, { rarity: "COMMON", rate: 0.55, color: "#A9A9A9" } ],
        itemPool: [
            { name: "Flash13", rarity: "LEGENDARY", img: "https://img5.pic.in.th/file/secure-sv1/Flash13.jpg" },
            { name: "Flash12", rarity: "EPIC", img: "https://img2.pic.in.th/pic/Flash12.jpg" },
            { name: "Flash11", rarity: "EPIC", img: "https://img5.pic.in.th/file/secure-sv1/Flash11.jpg" },
            { name: "Flash10", rarity: "RARE", img: "https://img2.pic.in.th/pic/Flash10.jpg" },
            { name: "Flash09", rarity: "RARE", img: "https://img5.pic.in.th/file/secure-sv1/Flash09.jpg" },
            { name: "Flash08", rarity: "RARE", img: "https://img2.pic.in.th/pic/Flash08.jpg" },
            { name: "Flash07", rarity: "UNCOMMON", img: "https://img5.pic.in.th/file/secure-sv1/Flash07.jpg" },
            { name: "Flash06", rarity: "UNCOMMON", img: "https://img2.pic.in.th/pic/Flash06.jpg" },
            { name: "Flash05", rarity: "COMMON", img: "https://img2.pic.in.th/pic/Flash05.jpg" },
            { name: "Flash04", rarity: "COMMON", img: "https://img5.pic.in.th/file/secure-sv1/Flash04.jpg" },
            { name: "Flash03", rarity: "COMMON", img: "https://img5.pic.in.th/file/secure-sv1/Flash03.jpg" },
            { name: "Flash02", rarity: "COMMON", img: "https://img5.pic.in.th/file/secure-sv1/Flash02.jpg" },
            { name: "Flash01", rarity: "COMMON", img: "https://img2.pic.in.th/pic/Flash01.jpg" },
        ]
    },
    {
        name: "20 Cosmic",
        themeColors: { base: 0x64748b, top: 0xef4444 },
        requiredStoneId: 2,
        dropRates: [ { rarity: "LEGENDARY", rate: 0.02, color: "#FFD700" }, { rarity: "EPIC", rate: 0.05, color: "#9400D3" }, { rarity: "RARE", rate: 0.13, color: "#1E90FF" }, { rarity: "UNCOMMON", rate: 0.25, color: "#32CD32" }, { rarity: "COMMON", rate: 0.55, color: "#A9A9A9" } ],
        itemPool: [
            { name: "Cosmic Beacon", rarity: "LEGENDARY", img: "https://img2.pic.in.th/pic/20.-Cosmic-Beacon.png" },
            { name: "River of Stars", rarity: "EPIC", img: "https://img5.pic.in.th/file/secure-sv1/19.-River-of-Stars.png" },
            { name: "Globular Cluster", rarity: "EPIC", img: "https://img2.pic.in.th/pic/18.-Globular-Cluster.png" },
            { name: "Galactic Cataclysm", rarity: "RARE", img: "https://img5.pic.in.th/file/secure-sv1/17.-Galactic-Cataclysm.png" },
            { name: "Rainbow Galaxy", rarity: "RARE", img: "https://img2.pic.in.th/pic/16.-Rainbow-Galaxy.png" },
            { name: "Hand of the Cosmos", rarity: "RARE", img: "https://img5.pic.in.th/file/secure-sv1/15.-Hand-of-the-Cosmos.png" },
            { name: "Pillars of Creation", rarity: "UNCOMMON", img: "https://img2.pic.in.th/pic/14.-Pillars-of-Creation.png" },
            { name: "Galactic Geode", rarity: "UNCOMMON", img: "https://img5.pic.in.th/file/secure-sv1/13.-Galactic-Geode.png" },
            { name: "Cosmic Egg", rarity: "UNCOMMON", img: "https://img2.pic.in.th/pic/12.-Cosmic-Egg.png" },
            { name: "Aura Rainbow Bridge", rarity: "COMMON", img: "https://img5.pic.in.th/file/secure-sv1/11.-Aura-Rainbow-Bridge.png" },
            { name: "Wormhole", rarity: "COMMON", img: "https://img2.pic.in.th/pic/10.-Wormhole.png" },
            { name: "Dark Nebula", rarity: "COMMON", img: "https://img5.pic.in.th/file/secure-sv1/9.-Dark-Nebula.png" },
            { name: "Stellar Wind Bubble", rarity: "COMMON", img: "https://img2.pic.in.th/pic/8.-Stellar-Wind-Bubble.png" },
            { name: "Galactic Collision", rarity: "COMMON", img: "https://img5.pic.in.th/file/secure-sv1/7.-Galactic-Collision.png" },
            { name: "Supernova Remnant", rarity: "COMMON", img: "https://img2.pic.in.th/pic/6.-Supernova-Remnant.png" },
            { name: "Mature Solar System", rarity: "COMMON", img: "https://img5.pic.in.th/file/secure-sv1/5.-Mature-Solar-System.png" },
            { name: "Protoplanetary Disk", rarity: "COMMON", img: "https://img2.pic.in.th/pic/4.-Protoplanetary-Disk.png" },
            { name: "Stellar Nursery", rarity: "COMMON", img: "https://img2.pic.in.th/pic/3-Stellar-Nursery.png" },
            { name: "Spiral Galaxy", rarity: "COMMON", img: "https://img5.pic.in.th/file/secure-sv1/2.-Spiral-Galaxy.png" },
            { name: "Supernova", rarity: "COMMON", img: "https://img5.pic.in.th/file/secure-sv1/1.-Supernova.png" },
        ]
    },
    {
        name: "20 Parallel World",
        themeColors: { base: 0x9333ea, top: 0xfacc15 },
        requiredStoneId: 3,
        dropRates: [ { rarity: "LEGENDARY", rate: 0.02, color: "#FFD700" }, { rarity: "EPIC", rate: 0.05, color: "#9400D3" }, { rarity: "RARE", rate: 0.13, color: "#1E90FF" }, { rarity: "UNCOMMON", rate: 0.25, color: "#32CD32" }, { rarity: "COMMON", rate: 0.55, color: "#A9A9A9" } ],
        itemPool: [
            { name: "Parallel World20", rarity: "LEGENDARY", img: "https://img5.pic.in.th/file/secure-sv1/MintingRareSet20.png" },
            { name: "Parallel World19", rarity: "EPIC", img: "https://img2.pic.in.th/pic/MintingRareSet19.png" },
            { name: "Parallel World18", rarity: "EPIC", img: "https://img5.pic.in.th/file/secure-sv1/MintingRareSet18.png" },
            { name: "Parallel World17", rarity: "RARE", img: "https://img2.pic.in.th/pic/MintingRareSet17.png" },
            { name: "Parallel World16", rarity: "RARE", img: "https://img5.pic.in.th/file/secure-sv1/MintingRareSet16.png" },
            { name: "Parallel World15", rarity: "RARE", img: "https://img2.pic.in.th/pic/MintingRareSet15.png" },
            { name: "Parallel World14", rarity: "UNCOMMON", img: "https://img5.pic.in.th/file/secure-sv1/MintingRareSet14.png" },
            { name: "Parallel World13", rarity: "UNCOMMON", img: "https://img2.pic.in.th/pic/MintingRareSet13.png" },
            { name: "Parallel World12", rarity: "UNCOMMON", img: "https://img5.pic.in.th/file/secure-sv1/MintingRareSet12.png" },
            { name: "Parallel World11", rarity: "COMMON", img: "https://img2.pic.in.th/pic/MintingRareSet11.png" },
            { name: "Parallel World10", rarity: "COMMON", img: "https://img5.pic.in.th/file/secure-sv1/MintingRareSet10.png" },
            { name: "Parallel World09", rarity: "COMMON", img: "https://img2.pic.in.th/pic/MintingRareSet09.png" },
            { name: "Parallel World08", rarity: "COMMON", img: "https://img5.pic.in.th/file/secure-sv1/MintingRareSet08.png" },
            { name: "Parallel World07", rarity: "COMMON", img: "https://img2.pic.in.th/pic/MintingRareSet07.png" },
            { name: "Parallel World06", rarity: "COMMON", img: "https://img5.pic.in.th/file/secure-sv1/MintingRareSet06.png" },
            { name: "Parallel World05", rarity: "COMMON", img: "https://img2.pic.in.th/pic/MintingRareSet05.png" },
            { name: "Parallel World04", rarity: "COMMON", img: "https://img2.pic.in.th/pic/MintingRareSet04.png" },
            { name: "Parallel World03", rarity: "COMMON", img: "https://img2.pic.in.th/pic/MintingRareSet03fd17ee057004533a.png" },
            { name: "Parallel World02", rarity: "COMMON", img: "https://img5.pic.in.th/file/secure-sv1/MintingRareSet02a2950ac9cf810aa3.png" },
            { name: "Parallel World01", rarity: "COMMON", img: "https://img5.pic.in.th/file/secure-sv1/MintingRareSet01.png" },
        ]
    }
];

export const moonStoneInfo = {
    0: { name: "Gold Moon Stone", color: "text-yellow-400", img: "https://img2.pic.in.th/pic/Gold-moon-stone.jpg", details: "A special stone used to summon heroes from the Zodiac." },
    1: { name: "Rainbow Moon Stone", color: "text-purple-400", img: "https://img5.pic.in.th/file/secure-sv1/Rainbow-moon-stone.jpg", details: "A mysterious stone that unlocks the power of the 13 Kingdoms." },
    2: { name: "Black Moon Stone", color: "text-gray-400", img: "https://img5.pic.in.th/file/secure-sv1/Black-moon-stone.jpg", details: "A dark stone that resonates with the vastness of the 20 Cosmic." },
    3: { name: "Red Moon Stone", color: "text-red-400", img: "https://img2.pic.in.th/pic/Red-moon-stone.jpg", details: "A vibrant stone required to mint the legendary 21 NFTs." },
};
